### ISSUE TITLE
Why throw?

### ISSUE THREAD

**Issue by bd82** [kdex/chi#4]
You have code in your parser that looks like:
```javascript
		this.RULE("BooleanLiteral", () => {
			const boolean = this.CONSUME(BooleanLiteral);
			if (boolean instanceof TrueLiteral) {
				return new True(boolean.meta.location, boolean.image);
			}
			else if (boolean instanceof FalseLiteral) {
				return new False(boolean.meta.location, boolean.image);
			}
			else {
				throw new Error(`Boolean literal should be "true" or "false"`);
			}
		});
```

And the Lexer is defined as:
```JavaScript
export class BooleanLiteral extends Literal {
	static PATTERN = NA;
}
export class TrueLiteral extends BooleanLiteral {
	static PATTERN = /true/;
}
export class FalseLiteral extends BooleanLiteral {
	static PATTERN = /false/;
}
```

In what case would  **this.CONSUME(BooleanLiteral)** not return a True or False literal?

**Comment by kdex** [comment]
Good find. 😆
Don't worry, it wasn't a bug with chevrotain or anything. It was really just my paranoia, as I wasn't sure if `BooleanLiteral` could be consumed in some weird edge case. I've removed it, including similar `throw`s of the same flavor. Thanks!

**Comment by bd82** [comment]
> Don't worry, it wasn't a bug with chevrotain or anything. 

Great 😄
